[versions]
intelliJPlatform = "2.9.0"
kotlin = "2.2.20"
changelog = "2.4.0"
kover = "0.9.2"

[libraries]
cucumberJava = { module = "io.cucumber:cucumber-java", version = "7.29.0" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
