[versions]
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
changelog = "2.5.0"
kover = "0.9.4"

[libraries]
cucumberJava = { module = "io.cucumber:cucumber-java", version = "7.33.0" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
